---
title: "Denuncias ambientales"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r paquetes, warning=FALSE, message=FALSE}
library (DT)
library (dplyr)
library (terra)
library (raster)
library (leaflet)
library (sf)
library (ggplot2)
library (plotly)
```

```{r datos, warning=FALSE, message=FALSE}
provincias <-
  st_read(
    "https://github.com/tpb728O-programaciongeoespacialr/2021ii/raw/main/datos/ign/delimitacion-territorial-administrativa/provincias.geojson",
    quiet = TRUE
  )
```


```{r}
denuncias <-
  st_read(
    "/vsicurl/https://raw.githubusercontent.com/MaureenArg/datostarea/master/denuncias.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
```
```{r}
st_crs (denuncias) <- 4326
```

```{r}
provincias <-
  provincias %>%
  st_transform(4326)
```

```{r}
nacientes <-
  st_read(
    "https://raw.githubusercontent.com/MaureenArg/datostarea/master/nacientes.geojson",
    quiet = TRUE
  )
```

```{r}
cuencas <-
  st_read(
    "https://raw.githubusercontent.com/MaureenArg/datostarea/master/cuencas.geojson",
    quiet = TRUE
  )
```

```{r}
rios <-
  st_read(
    "https://raw.githubusercontent.com/MaureenArg/datostarea/master/rios.geojson",
    quiet = TRUE
  )
```

```{r}
altitud <-
  rast(
    "/vsicurl/https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/master/datos/worldclim/altitud.tif"
  )
```


```{r}
denu_depu <-
  st_read(
    "/vsicurl/https://raw.githubusercontent.com/MaureenArg/datostarea/master/denu_depu.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
```

```{r}
st_crs (denu_depu) <- 4326
```

```{r}
denu_depu %>%
  st_drop_geometry()%>%
  select (TIPO_den, año, TIPO_inf, CATEGORIA_) %>%
    datatable (rownames= FALSE, filter= "top", class= "hover cell-border stripe", caption= "Tabla 1: Tipo de denuncias ambientales según año")
```





